site_name: 'EKS Distro'
site_description: 'Amazon EKS Distro'
site_author: 'The EKS-D contributors'
site_url: 'https://distro.eks.amazonaws.com'
repo_name: 'aws/eks-distro'
repo_url: 'https://github.com/aws/eks-distro'
edit_uri: 'edit/main/docs/contents'
copyright: 'Copyright &copy; 2020 Amazon'
docs_dir: 'contents'
nav:
- Home: 'index.md'
- Users:
  - Overview: 'users/index.md'
  # - Architecture: 'users/architecture.md'
  - Install EKS Distro:
    - Partners: 'users/install/partners.md'
    - Community:
      - Install with kubeadm (bare metal or VM): 'users/install/kubeadm-onsite.md'
      - Install with kubeadm (tested on Raspberry Pi): 'users/install/kubeadm.md'
      - Install with kOps: 'users/install/kops.md'
      - Install with kubeinit (Ansible on Libvirt hosts): 'users/install/kubeinit.md'
- Community:
  - Overview: 'community/overview.md'
  - Contributing: 'community/contributing.md'
  - FAQ: 'community/faq.md'
  - Governance: 'community/governance.md'
  - Code of Conduct: 'community/code_of_conduct.md'
extra:
  social:
  - icon: 'fontawesome/brands/twitter'
    link: 'https://twitter.com/awscloud'
theme:
  name: 'material'
  features:
  - navigation.tabs
  - navigation.instant
  custom_dir: 'theme'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  font:
      text: 'Oxygen'
      code: 'Oxygen Mono'
  palette:
    primary: 'white'
  highlightjs: true
  hljs_languages:
  - 'yaml'
  - 'json'
  - 'bash'
markdown_extensions:
- pymdownx.snippets
- toc:
    permalink: true
- admonition
- codehilite:
    linenums: true
    use_pygments: False
