name: base-image-pr-notifier
on:
  pull_request_target:
    types: [opened]
permissions: {}
jobs:
  baseimage-pr-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and notify Slack
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [[ "$PR_AUTHOR" == "eks-distro-pr-bot" && ( "$PR_TITLE" == *"Update base image"* || "$PR_TITLE" == *"Update builder-base image"* || "$PR_TITLE" == *"Update golang"* || "$PR_TITLE" == *"Update GIT_TAG and GOLANG_VERSION"* ) ]]; then
            payload=$(jq -n \
              --arg repo "$GITHUB_REPOSITORY" \
              --arg pr_title "$PR_TITLE" \
              --arg pr_url "$PR_URL" \
              '{repo: $repo, pr_title: $pr_title, pr_url: $pr_url}')
            curl -X POST -H 'Content-Type: application/json' --data "$payload" "$SLACK_WEBHOOK"
            echo "Base image update detected - Slack notification sent"
          else
            echo "Not a base image update PR - Skipping notification"
          fi
          exit 0
