name: base-image-pr-notifier
on:
  pull_request_target:
    types: [opened]
permissions: {}
jobs:
  baseimage-pr-notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title and notify Slack
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [[ "$PR_TITLE" == *"Update base image"* || "$PR_TITLE" == *"Update builder-base image"* || "$PR_TITLE" == *"Update golang"* || "$PR_TITLE" == *"Update GIT_TAG and GOLANG_VERSION"* ]]; then
            curl -X POST $SLACK_WEBHOOK
            echo "Base image update detected - Slack notification sent"
          else
            echo "Not a base image update PR - Skipping notification"
          fi
          exit 0
